apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robot-deployment
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://gitea-app.git
    targetRevision: HEAD
    path: manifests
  syncPolicy:
    automated: {}